[tox]
minversion = 4.18.1
envlist =
    py{310,311,312}-django42-wagtail{63,70,72}
    ; 6.3, 7.0 and 7.2 work with Django 5.1 and 5.2
    py{310,311,312,313}-django{51,52}-wagtail{63,70,72}
    ; Django 5.2 works with Python 3.14
    py{314}-django52-wagtail{63,70,72}

[testenv]
extras = testing
commands = coverage run testmanage.py test --deprecation all {posargs: -v 2}

basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14

deps =
    coverage

    django42: Django>=4.2,<4.3
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3

    wagtail63: wagtail>=6.3,<6.4
    wagtail70: wagtail>=7.0,<7.1
    wagtail72: wagtail>=7.2,<7.3

[testenv:future]
extras = testing
commands = coverage run testmanage.py test --deprecation all {posargs: -v 2}
basepython = python3.13
deps =
    coverage
    ; Test compatibility with upcoming Wagtail and Django versions
    https://github.com/wagtail/wagtail/archive/refs/heads/main.zip
    https://github.com/django/django/archive/refs/heads/main.zip

[testenv:interactive]
basepython = python3.13

commands_pre =
    python {toxinidir}/testmanage.py makemigrations
    python {toxinidir}/testmanage.py migrate
    python {toxinidir}/testmanage.py shell -c "from django.contrib.auth.models import User;(not User.objects.filter(username='admin').exists()) and User.objects.create_superuser('admin', 'super@example.com', 'changeme')"
    python {toxinidir}/testmanage.py createcachetable

commands =
    {posargs:python testmanage.py runserver 0.0.0.0:8020}

setenv =
    INTERACTIVE = 1
