# Generated by Django 5.2.17 on 2026-08-20 11:35

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models
from wagtail import VERSION as WAGTAIL_VERSION

if WAGTAIL_VERSION >= (8, 0):
    import swapper

    PAGE_MODEL_NAME = swapper.get_model_name("wagtailcore", "Page")
else:
    PAGE_MODEL_NAME = "wagtailcore.Page"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modeladmintest", "0001_initial"),
        ("modeladmintest_pages", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpagecarouselitem",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carousel_items",
                to="modeladmintest_pages.eventpage",
            ),
        ),
        migrations.AddField(
            model_name="relatedlink",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=PAGE_MODEL_NAME,
            ),
        ),
        migrations.AddField(
            model_name="relatedlink",
            name="link_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="modeladmintest.customdocument",
            ),
        ),
        migrations.AddField(
            model_name="relatedlink",
            name="link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=PAGE_MODEL_NAME,
            ),
        ),
        migrations.AddField(
            model_name="eventpagespeaker",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="modeladmintest.customimage",
            ),
        ),
        migrations.AddField(
            model_name="eventpagespeaker",
            name="link_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="modeladmintest.customdocument",
            ),
        ),
        migrations.AddField(
            model_name="eventpagespeaker",
            name="link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=PAGE_MODEL_NAME,
            ),
        ),
        migrations.AddField(
            model_name="eventpagespeaker",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AddField(
            model_name="eventpagespeaker",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speakers",
                related_query_name="speaker",
                to="modeladmintest_pages.eventpage",
            ),
        ),
        migrations.AddField(
            model_name="eventpagespeakeraward",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AddField(
            model_name="eventpagespeakeraward",
            name="speaker",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="modeladmintest.eventpagespeaker",
            ),
        ),
        migrations.AddField(
            model_name="headcountrelatedmodelusingpk",
            name="event_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="head_counts",
                to="modeladmintest_pages.eventpage",
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="solobook",
            name="author",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="modeladmintest.author"
            ),
        ),
        migrations.AddField(
            model_name="translatablebook",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="modeladmintest.author"
            ),
        ),
        migrations.AddField(
            model_name="translatablebook",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="modeladmintest.customimage",
            ),
        ),
        migrations.AddField(
            model_name="translatablebook",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customrendition",
            unique_together={("image", "filter_spec", "focal_point_key")},
        ),
        migrations.AlterUniqueTogether(
            name="eventcategory",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="eventpagecarouselitem",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="eventpagespeaker",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="eventpagespeakeraward",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="translatablebook",
            unique_together={("translation_key", "locale")},
        ),
        migrations.CreateModel(
            name="EventPageRelatedLink",
            fields=[
                (
                    "relatedlink_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="modeladmintest.relatedlink",
                    ),
                ),
                (
                    "translation_key",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_links",
                        to="modeladmintest_pages.eventpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
            bases=("modeladmintest.relatedlink", models.Model),
        ),
    ]
