# Generated by Django 6.1 on 2026-08-19 21:36

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basepage", "0003_basepage_latest_revision_and_more"),
        ("modeladmintest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessChild",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("basepage.basepage",),
        ),
        migrations.CreateModel(
            name="BusinessIndex",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("basepage.basepage",),
        ),
        migrations.CreateModel(
            name="BusinessNowherePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("basepage.basepage",),
        ),
        migrations.CreateModel(
            name="BusinessSubIndex",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("basepage.basepage",),
        ),
        migrations.CreateModel(
            name="EventIndex",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True, max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("basepage.basepage",),
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                ("date_from", models.DateField(null=True, verbose_name="Start date")),
                (
                    "date_to",
                    models.DateField(
                        blank=True,
                        help_text="Not required if event is on a single day",
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                (
                    "time_from",
                    models.TimeField(blank=True, null=True, verbose_name="Start time"),
                ),
                (
                    "time_to",
                    models.TimeField(blank=True, null=True, verbose_name="End time"),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        max_length=255,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                ("cost", models.CharField(max_length=255)),
                ("signup_link", models.URLField(blank=True)),
                (
                    "categories",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="modeladmintest.eventcategory"
                    ),
                ),
                (
                    "feed_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="modeladmintest.customimage",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("custom_see_panel_setting", "Can see the panel."),
                    ("other_custom_see_panel_setting", "Can see the panel."),
                ],
            },
            bases=("basepage.basepage",),
        ),
        migrations.CreateModel(
            name="SimplePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                ("content", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("basepage.basepage",),
        ),
        migrations.CreateModel(
            name="VenuePage",
            fields=[
                (
                    "basepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("capacity", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("basepage.basepage",),
        ),
        migrations.CreateModel(
            name="SingleEventPage",
            fields=[
                (
                    "eventpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="modeladmintest_pages.eventpage",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short text to describe what is this action about",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("modeladmintest_pages.eventpage",),
        ),
    ]
